name: SimpleTS3AppCD

# Contains all the things to do after code is merged into master
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  Test:
    name: RunCD
    runs-on: ubuntu-latest
    env:
      working-directory: ./

    steps:
      - uses: actions/checkout@v2
        
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm ci

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ${{env.working-directory}}
          file: ${{env.working-directory}}/Dockerfile
          platforms: linux/amd64
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/simple-ts3-app:latest
          
